#!/bin/bash

#echo $SCRIBER_HOME
CWD="$PWD"

if [ -d "$SCRIBER_HOME" ]
then
  #echo "HI"
  cd $SCRIBER_HOME
else
  echo "SCRIBER_HOME environment variable not set."
  exit 1
fi

numArgs=$#

if [ $numArgs -ne 1 ]
then
  echo "Usage: "
  echo "      ./scriber myAudioFile.wav"
  echo "Or: "
  echo "      ./scriber youtube-url"
  exit 1
fi

filepath=$1

#echo $filepath
if [[ "$filepath" == *"youtube"* ]] 
then
  echo "Contains youtube"
  ./youtube_mp3.py $filepath
  echo "done"
  filepath="$SCRIBER_HOME/tmp/target.wav"
  mv *.wav $filepath
else
  if [ -e "$filepath" ]
  then
    echo "Reading $filepath ..."
  else
    echo "Must use absolute file path."
    exit 1
  fi
fi

filename=$(basename "$filepath")
ext="${filename##*.}"
fmt=""

if [ $ext = "wav" ]
then
  fmt="wav"
else
  echo "Currently, python only takes 'wav' files, not mp3's. Please convert your "
  echo "your audio to 'wav' format first."
  exit 1
  fmt="mpeg"
fi

python spectrogram.py $filepath
sed "s@{{filepath}}@$filename@g" template/index.html > tmp/tmp
sed "s@{{fmt}}@$fmt@g" tmp/tmp > tmp/index.html
rm -f tmp/tmp

cp $filepath tmp
cp -r css tmp
cp -r js tmp

cd tmp 
python -m SimpleHTTPServer
